#ifndef SEA_TOON_CORE_INCLUDED
#define SEA_TOON_CORE_INCLUDED

#define SHADOW_MIN_THRESHOLD 0.0
#define SHADOW_MAX_THRESHOLD 0.2

#define BANGS_SHADOW_EXTEND_LENGTH 0.005

#define HAIR_SHADOW_MASK_MIN_THRESHOLD 0.0
#define HAIR_SHADOW_MASK_MAX_THRESHOLD 0.02
#define HAIR_SPECULAR_ANISO_MIN -0.05
#define HAIR_SPECULAR_ANISO_MAX 0.05

#define OUTLINE_WIDTH_SCALING_FACTOR 0.01

#define RIM_LIGHT_WIDTH_SCALING_FACTOR 10
#define RIM_LIGHT_DEPTH_DIFF_MIN_THRESHOLD 0.1
#define RIM_LIGHT_DEPTH_DIFF_MAX_THRESHOLD 0.12
#define RIM_LIGHT_FRESNEL_MIN_THRESHOLD 0.12
#define RIM_LIGHT_FRESNEL_MAX_THRESHOLD 0.15

half3 ToonDiffuse(half3 albedo, half3 rampColor, half shadowMask)
{
    half3 ramp = lerp(rampColor, 1.0, shadowMask);
    return 0.5*albedo*ramp;
}

#endif
